apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-api-gateway-service
spec:
  selector:
    matchLabels:
      app: grpc-api-gateway-service
  template:
    metadata:
      labels:
        app: grpc-api-gateway-service
    spec:
      containers:
        - name: grpc-api-gateway-service
          image: mafeidev/grpc-spring-lb-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DEFAULT_ZONE
              value: http://eureka-server-deployment-0.eureka.default.svc.cluster.local:8085/eureka
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-api-gateway-service
spec:
  selector:
    app: grpc-api-gateway-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
